export const ADD_LIST = "ADD_LIST";
export const REMOVE_LIST = "REMOVE_LIST";
export const LIST_CLICKED = "LIST_CLICKED";

export const ADD_POSITION = "ADD_POSITION";
export const POSITION_COMPLETE_TOGGLE = "POSITION_COMPLETE_TOGGLE";